version: '3.8'


services:

  sample:
    container_name: crudnews_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    expose:
      - 3001
    environment:
      - CHOKIDAR_USEPOLLING=true
